# -*- coding: utf-8 -*-
"""punto4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bd7fRKve6CJTxBQ2MwT8fJoYfG6Uj-d
"""

print("Vamo a ve si los números que coloques son multiplos uno del otro")

a=int(input("Coloca un primer número: "))
b=int(input("Coloca un segundo número: "))

if a % b == 0:
    print(f"{a} Es multiplo de {b}")

else:
    print(f"{a} NO es multiplo de {b}")