# -*- coding: utf-8 -*-
"""punto6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16YeIXMCZgYQVsrMd2dozvauX_s7GoXuK
"""

print("Vamos a ver si el caracter que ingreses sera una vocal o consonante")
x= input("Coloca la letra que desees: ")

def vocal_o_consonante(x):
    if x in ("a", "A", "e","E","i","I","o","O","u","U","á","é","í","ó","ú"):
        print("Ingresaste una vocal")
    else:
        print("Ingresaste una consonante ")

print (vocal_o_consonante(x))