# -*- coding: utf-8 -*-
"""Punto8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VknVzw_j3qcd-6JsLS81E_idJIg3-q2n
"""

##Punto 8

####Escriba un programa al que se le ingrese la frecuencia de una onda en hz y como salida arroje en que parte del espectro electromagnético se encuentra.


######Pedirle a la persona un valor de onda y si desea elevar ese número por algun otro, esto para dar mas variedad a la frecuencia de onda

valor_deseado = float(input("El número que eliges es "))
elevar_numero = float(input("Por cual número deseas elevar el que elegiste anteriormente? "))
frecuencia_de_onda_hz = valor_deseado**elevar_numero
print("La frecuencia en hz de la onda es " +str(frecuencia_de_onda_hz))

#Ahora utilizaremos la imagen del github, en la que aparece los rangos del espectro visible para establecer un codigo de condicional if-else para saber dentro de que rango esta

if 1 <= frecuencia_de_onda_hz < 10**3.5:
  print("La onda se encuentra en frecuencias extremadamente bajas")
elif 10**3.5 <= frecuencia_de_onda_hz < 10**8.5:
  print("La onda se encunetra en Ondas radioeléctricas")
elif 10**8.5 <= frecuencia_de_onda_hz < 10**11.5:
  print("La onda se encunetra en Microondas")
elif 10**11.5 <= frecuencia_de_onda_hz < 10**14.5:
  print("La onda se encunetra en Infrarojas")
elif 10**14.5 <= frecuencia_de_onda_hz < 10**15.5:
  print("La onda se encunetra en Ultravioletas")
elif 10**15.5 <= frecuencia_de_onda_hz < 10**17.5:
  print("La onda se encunetra en Rayos X")
elif 10**17.5 <= frecuencia_de_onda_hz < 10**19.5:
  print("La onda se encunetra en Rayos Gamma")
elif 10**19.5 <= frecuencia_de_onda_hz:
  print("La onda se encunetra en Rayos cosmicos")