# -*- coding: utf-8 -*-
"""punto2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YFGp-7aiS95bKy-7ZnFXgI-Gt8-93MsN
"""

a=float(input("Ingresa tu primer número: "))
b=float(input("Ingresa tu segundo número: "))
c=float(input("Ingresa tu tercer número: "))

#Es necesario que no sean iguales, por eso utilizaremos el simbolo !

if a!=b and a!=b and b!=c:
    if a>b:
        if a>c:
            print("El numero mayor es:",a)
        else:
            print ("El número mayor es: ",c)
    else:
        if b>c:
            print("El número mayor es: ",b)
        else:
            print("El número mayor es: ",c)
else:
    print("Ingrese otros 3 números porque F, no se puede saber cual es mayor a cual xd")