# -*- coding: utf-8 -*-
"""Punto10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FKkHq9c3tDkfPhyGGmnaVL4zMvNcBf5d
"""

vel_luz= float(2.99*(10**8)) #Valor aproximado de la velocidad de la luz a dos decimales
vel_sonido = float(343.2) #Velocidad del sonido en el aire a 20 grados
vel_ssc_Tuatara = float(141.111) #Velocidad auto mas rapido, SSC Tuatara, 508 km/h
vel_bolt = float (12.42) #Se tomo su velocidad maxima alcanzada en 2009 cuando corrio los 100 metros

distancia_en_metros= float(input("La distancia en metros sera= "))

tiempo_luz = float(distancia_en_metros/vel_luz)
print("El tiempo que le tomara a la luz recorrer la distancia sera de " +str(tiempo_luz)+ " segundos")
tiempo_sonido = float(distancia_en_metros/vel_sonido)
print("El tiempo que le tomara al sonido recorrer la distancia sera de " +str(tiempo_sonido)+ " segundos")
tiempo_ssc_Tuatara = float(distancia_en_metros/vel_ssc_Tuatara)
print("El tiempo que le tomara al SSC Tuatara recorrer la distancia sera de " +str(tiempo_ssc_Tuatara)+ " segundos")
tiempo_bolt = float(distancia_en_metros/vel_bolt)
print("El tiempo que le tomara a Usain Bolt recorrer la distancia sera de " +str(tiempo_bolt)+ " segundos")

tiempo_luz = float(tiempo_luz/60)
print("El tiempo que le tomara a la luz recorrer la distancia sera de " +str(tiempo_luz)+ " minutos")
tiempo_sonido = float(tiempo_sonido/60)
print("El tiempo que le tomara al sonido recorrer la distancia sera de " +str(tiempo_sonido)+ " minutos")
tiempo_ssc_Tuatara = float(tiempo_ssc_Tuatara/60)
print("El tiempo que le tomara al SSC Tuatara recorrer la distancia sera de " +str(tiempo_ssc_Tuatara)+ " minutos")
tiempo_bolt = float(tiempo_bolt/60)
print("El tiempo que le tomara a Usain Bolt recorrer la distancia sera de " +str(tiempo_bolt)+ " minutos")